CREATE TABLE IF NOT EXISTS user (
id INT NOT NULL AUTO_INCREMENT,
user_name VARCHAR(255) NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS event (
id INT NOT NULL AUTO_INCREMENT,
event_name VARCHAR(255) NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS file (
id INT NOT NULL AUTO_INCREMENT,
file_name VARCHAR(255) NOT NULL,
PRIMARY KEY(id)
);