CREATE TABLE IF NOT EXISTS user (
user_id INT NOT NULL AUTO_INCREMENT UNIQUE,
user_name VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL,
PRIMARY KEY(user_id)
);

CREATE TABLE IF NOT EXISTS event (
event_id INT NOT NULL AUTO_INCREMENT UNIQUE,
event_name VARCHAR(255) NOT NULL,
user_id INT NOT NULL,
file_id INT NOT NULL,
PRIMARY KEY(event_id)
);


CREATE TABLE IF NOT EXISTS file (
file_id INT NOT NULL AUTO_INCREMENT UNIQUE,
file_name VARCHAR(255) NOT NULL,
PRIMARY KEY(file_id)
);



